# Generated by Django 2.2.4 on 2019-10-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(default=0)),
                ('doctor_name', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=20)),
                ('timingslot1', models.IntegerField(default=0)),
                ('timingslot2', models.IntegerField(default=0)),
                ('timingslot3', models.IntegerField(default=0)),
                ('timingslot4', models.IntegerField(default=0)),
                ('timingslot5', models.IntegerField(default=0)),
                ('timingslot6', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('date', models.CharField(default='11/10/2019', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('pid', models.IntegerField(default=0)),
                ('date', models.DateField(default='2019-10-11')),
                ('files', models.FileField(upload_to='media')),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
