# Generated by Django 2.2.4 on 2019-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combinedmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=10)),
                ('patientname', models.CharField(max_length=10)),
            ],
        ),
    ]
