# Generated by Django 2.2.4 on 2019-10-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedmodel',
            name='did',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='combinedmodel',
            name='pid',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
