# Generated by Django 2.2.4 on 2019-10-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorportal', '0003_auto_20191011_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointmentmodel',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
