# Generated by Django 2.2.4 on 2019-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('password', models.CharField(max_length=24124)),
                ('name', models.CharField(max_length=51515)),
            ],
        ),
    ]
