# Generated by Django 2.2.4 on 2019-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='name',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
